path: data/yolo

train: images/train
val: images/val
test: images/test

names:
  0: aoxian
  1: budaodian
  2: cahua
  3: jupi
  4: loudi
  5: pengshang
  6: qikeng
  7: tucengkailie
  8: tufen
  9: zangdian